---
openapi: 3.0.0
info:
   version: 1.3.0
   title: singletest77 open api specification
   description: single API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8008
     description: single
tags:
- name: single
paths:
   "/single":
      post:
         tags:
         -  single
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/single"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      single:
         type: object
         properties:
            Name:
               type: "string"
               description: Description